Added ungrouping X if grouped
entdec/satis pull request #37
Opened 2023-05-02 08:57 UTC by rparse

2023-05-03 09:11 UTC, WaQasRPL requested changes
it works well but i guess may be small enhancements will improve the the user experience

change X text to icon (same color) as search table or clear dropdown
display X only if the column has grouped by enabled.

2023-05-03 12:03 UTC, rparse commented
> it works well but i guess may be small enhancements will improve the the user experience
> 
> change X text to icon (same color) as search table or clear dropdown display X only if the column has grouped by enabled.

Fixed the Suggestions, Please have a look.
Thank you!!!

2023-05-03 12:11 UTC, WaQasRPL approved these changes

2023-08-31 07:40 UTC, tdegrunt approved these changes

2023-08-31 07:40 UTC, merged